spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coursestudentdb
    username: postgres
    password: 123senha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html